### ISSUE TITLE
referring to built-in type queue as a remote type;

### ISSUE THREAD

**Issue by ana-jd** [processone/p1_utils#10]
When compiling on ubuntu 14.04 we have this issue : 
==> p1_utils (compile)
Compiled src/p1_fsm.erl
Compiled src/p1_server.erl
Compiled src/p1_utils.erl
Compiled src/p1_nif_utils.erl
src/p1_queue.erl:22: referring to built-in type queue as a remote type; please take out the module name

**Comment by prefiks** [comment]
Hello,

Could you tell me what erlang version are you using? i am unable to reproduce that here.

**Comment by ana-jd** [comment]
$ erl -noshell -eval 'erlang:display(erlang:system_info(system_version))' -eval 'init:stop()'
"Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [kernel-poll:false]\n"

**Comment by prefiks** [comment]
Unfortunately this version is not supported, it requires at least 17.5 (could also work with older versions from R17, but not 100% sure about it). Problem described here could possibly get workaround, but this module uses maps feature of erlang not available in this version, so even after trying to fix this compilation will fail later.

**Comment by ana-jd** [comment]
OK i will upgrade thank you very much.
