### ISSUE TITLE
Error in eunit

### ISSUE THREAD

**Issue by mremond** [processone/p1_utils#12]
When running eunit, I get the following error:

```
=ERROR REPORT==== 9-Feb-2021::15:24:47.837384 ===
failed to create directory "/home/runner/work/p1_utils/p1_utils/eacces_queue/p1_queue": permission denied
=CRASH REPORT==== 9-Feb-2021::15:24:47.837613 ===
  crasher:
    initial call: p1_file_queue:init/1
    pid: <0.1058.0>
    registered_name: []
    exception exit: eacces
      in function  gen_server:init_it/6 (gen_server.erl, line 401)
    ancestors: [p1_utils_sup,<0.951.0>]
    message_queue_len: 0
    messages: []
    links: [<0.952.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 28
    reductions: 2960
  neighbours:
```

**Comment by prefiks** [comment]
Now that is strange stuff, do you have /home/runner/work/p1_utils/p1_utils/eacces_queue/ dir? It looks like rebar got eaccess from system error somehow?

**Comment by prefiks** [comment]
Ah, no that name is part of test.

**Comment by prefiks** [comment]
You are getting that error on linux or mac?

**Comment by badlop** [comment]
That error is triggered on purpose by 
https://github.com/processone/p1_utils/blob/2b0b2e07e282988ba8ecd8b23c558662c3573aad/test/p1_queue_test.erl#L429

I get it, and the eunit result is:
> 70 tests, 0 failures

**Comment by mremond** [comment]
I get that when running on Linux from a Github Runner (Docker image).

**Comment by badlop** [comment]
As explained before, that error message indicates that the testing works correctly :)

It can be seen on Travis too:
  https://travis-ci.org/github/processone/p1_utils/jobs/764239850#L260
  
So, can we close this issue?

**Comment by badlop** [comment]
Obviously, that error message is also displayed when running the tests in github actions, and that means the test worked correctly:
https://github.com/processone/p1_utils/runs/2951096057?check_suite_focus=true
