### ISSUE TITLE
don't include rebar3_hex plugin when publishing packages

### ISSUE THREAD

**Issue by ferd** [processone/p1_utils#3]
The rebar3 hex plugin should be a global plugin a user installs (see https://hex.pm/docs/rebar3_publish) so that people can use the package without needing to fetch the hex plugin, which is not required at all to run code or compile it.

**Comment by badlop** [comment]
This has been finally fixed in 58d0f917f1b3d7c21e4698b27a63ce2a8ed7c0c0 , and similar commits for the other libraries.
