### ISSUE TITLE
Release 1.0.19 to Hex.pm

### ISSUE THREAD

**Issue by dyf182** [processone/p1_utils#9]
Is it possible to release 1.0.19 hex package please, i'm currently having issues with dependency chains with rebar unable to find the correct packages in the registry when pulling and building processone/fastxml dependency.

Thankyou

**Comment by dyf182** [comment]
here's the error i see for more context
```
===> Compiling rebar3_gpb_plugin
===> Package p1_utils-1.0.19 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /home/jenkins/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /home/jenkins/.cache/rebar3/hex/default/packages.idx
===> Package not found in registry: p1_utils-1.0.19.
```

**Comment by prefiks** [comment]
Yes, i tagged yesterday new releases for couple of our packages, i will try to upload them to hex soon.

**Comment by dyf182** [comment]
Great, many thanks!

**Comment by prefiks** [comment]
New version landed in hex repository.
